language: php

sudo: false

php:
    - '7.0.2'

before_install:
    - phpenv config-rm xdebug.ini

install:
    - travis_retry composer self-update --no-progress
    - travis_retry composer install --no-progress --no-interaction
    - travis_retry composer info --installed --tree

script:
    - ./bin/atoum
